version: '2'

services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    network_mode: bridge

  selenium-hub:
    container_name: jtowler/selenium-hub
    image: selenium-hub
    ports:
      - "4444"
    network_mode: bridge
    environment:
      - VIRTUAL_HOST=selenium.company.com
    depends_on:
      - nginx

  selenium-node:
    image: jtowler/selenium-node
    network_mode: bridge
    depends_on:
      - selenium-hub
    links:
      - selenium-hub
